language: node_js
node_js:
  - "0.12"
install:
  - npm install -g bower
  - npm install -g gulp
  - npm install
  - bower install
before_script:
  - gulp build
script: gulp test
notifications:
  email:
    - janrembold@gmail.com