language: node_js
node_js:
#  - "5"
  - "4"
  - "0.12"
#  - "0.10"
install:
  - npm install -g bower
  - npm install -g gulp
  - npm install
  - bower install
before_script:
  - gulp build
script: gulp test
